version: '3.3'

services: 
    redis:
        image: redis:latest
        ports: 
            - "6379:6379"
        networks: 
            - app-network 
    api:
        build: "."
        depends_on: 
            - redis
        ports:
            - "5000"
        environment:
            REDISHOST: redis:6379
        restart: "always"
        networks: 
            - app-network
        deploy:
            replicas: 5
    nginx:
        image: nginx:latest
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on: 
            - api
        ports: 
            - "80:80"
        networks: 
            - app-network

#Docker Networks
networks: 
    app-network:
        driver: bridge